source "https://rubygems.org"

gem "fastlane", "~> 2.220"

# Include any plugins fastlane installs into Pluginfile.
plugins_path = File.join(File.dirname(__FILE__), "fastlane", "Pluginfile")
eval_gemfile(plugins_path) if File.exist?(plugins_path)
